[app]
10.0.3.113 ansible_user=ubuntu ansible_ssh_private_key_file=/var/lib/jenkins/.ssh/mac_pass.pem
10.0.4.45 ansible_user=ubuntu ansible_ssh_private_key_file=/var/lib/jenkins/.ssh/mac_pass.pem

[db]
10.0.3.171 ansible_user=ubuntu ansible_ssh_private_key_file=/var/lib/jenkins/.ssh/mac_pass.pem

[bastion]
localhost ansible_connection=local