---
- name: Install PostgreSQL on DB Node
  hosts: db
  become: yes

  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Start PostgreSQL
      service:
        name: postgresql
        state: started
        enabled: yes
        